### ISSUE TITLE
[Feature request] I need the output files in another branch instead of `master`.

### ISSUE THREAD

**Issue by vietnhatthai** [vn7n24fzkq/github-profile-summary-cards#111]
Hi, 

How to change the output files of `github action` to another branch instead of `master`?

Thanks.

**Comment by vietnhatthai** [comment]
I don't want the output folder in `branch master`.

![image](https://user-images.githubusercontent.com/60825385/198815963-78c2542b-2287-427b-bc82-70aec7e8bc70.png)

Can you make folder `profile-summary-card-output` in another branch?

**Comment by vn7n24fzkq** [comment]
Sorry for the late reply.
Currently, we put everything in the master branch, it's not an option yet but we can add a parameter for that.

**Comment by jnan806** [comment]
> Sorry for the late reply. Currently, we put everything in the master branch, it's not an option yet but we can add a parameter for that.

It looks good, when will it been complemented ?

**Comment by vietnhatthai** [comment]
Thanks!! #117
