### ISSUE TITLE
[BUG] Invalid status code:128

### ISSUE THREAD

**Issue by Key5n** [vn7n24fzkq/github-profile-summary-cards#129]
**Describe the bug**
like #113 #104 ,Running github actions, my workflow said invalid status code:128.  

I fixed this problem by giving "Read and write permission to GITHUB_TOKEN" like below.
But I can't miss why I got stuck although followed your tutorial.
![github_profile_summary_fixed](https://user-images.githubusercontent.com/90585006/212334577-f58111af-f693-47de-8cc6-0714da8d19f4.png)

It seems that it couldn't commit and push updated contents.  
Do you know the reason? I am new to Github Actions.

**To Reproduce**
Follow your tutorial

**Expected behavior**
Finish tutorial

**Screenshots**
![github_profile_summary_cards_failure](https://user-images.githubusercontent.com/90585006/212333564-0930e8c4-057d-4a31-8c5e-908c38762943.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 108.0.2

**Comment by vn7n24fzkq** [comment]
Hi @key5n , sorry for the late reply.
Can you re-trigger the workflow?
For some reason, the git push failed sometimes.

**Comment by key5n** [comment]
Thank you for the reply.
I re-triggered it with no default write permission to GITHUB_TOKEN.
But I faced the same error.
I also followed the tutorial again, but nothing has changed.

With default write permission to GITHUB_TOKEN, it succeeded though.

**Comment by vn7n24fzkq** [comment]
Great!
Seems we missing that permission in the document.
Thanks for the issue.

**Comment by cimadai** [comment]
I faced to same issue and finally I succeeded to push with select `Read and write permissions` in `Workflow permissions` section.

**Comment by Key5n** [comment]
Yes, that is another solution.
If you mind giving read and write permission to GITHUB_TOKEN for all-scopes, we can avoid this by only adding `content: read` permission to the job.
I verified it works on my repository.

**Comment by vn7n24fzkq** [comment]
Great! I think that is a better solution.
