### ISSUE TITLE
[BUG] Warning: Invalid status code: 128 Error: git push 

### ISSUE THREAD

**Issue by swastkk** [vn7n24fzkq/github-profile-summary-cards#131]
Getting this error while running the workflow file.
```Warning: Commit failed. Retry...
Warning: Commit failed. Retry...
Error: Error: git push 
  
 Invalid status code: 128
Error: git push 
```
Please help :")

**Comment by vn7n24fzkq** [comment]
Hi, @swastkk.
It seems the same as #129.
Can you try to add written permission and re-trigger again?

**Comment by swastkk** [comment]
> Hi, @swastkk. It seems the same as #129. Can you try to add written permission and re-trigger again?

Have tried but still facing issue, 
Is there any chance that having that  Repo  private, causing this workflow failure?

**Comment by ethanknights** [comment]
@swastkk my repo's were public when toying with this, but I encountered the same error (so its not due to repo visibility).

**Comment by vn7n24fzkq** [comment]
We add the required write permission in action now, it should be fixed.
https://github.com/vn7n24fzkq/github-profile-summary-cards#github-actions-usage
