### ISSUE TITLE
[Discuss] Change chart x axis tick

### ISSUE THREAD

**Issue by vn7n24fzkq** [vn7n24fzkq/github-profile-summary-cards#14]
I want to change x axis tick, because current tick just looks a bit crowded.

Before
![image](https://user-images.githubusercontent.com/20241522/95012998-cb7c7580-066f-11eb-8be6-98a431eaaca4.png)
After
![image](https://user-images.githubusercontent.com/20241522/95012972-8fe1ab80-066f-11eb-8c2b-4e98a950de95.png)

I would merge to release branch if it is fine.

**Comment by abc873693** [comment]
Amazing

**Comment by vn7n24fzkq** [comment]
It's release now!
