### ISSUE TITLE
[BUG]Output of info in Excluded languages is wrong.

### ISSUE THREAD

**Issue by shunsuke6** [vn7n24fzkq/github-profile-summary-cards#142]
**Describe the bug**
Output of info in Excluded languages is wrong.

**Additional context**
Here useOfset is used.
https://github.com/MiranDaniel/github-profile-summary-cards/blob/48bc8a05e4bdd4e5b8898de4ca166fb2c91bf6d7/src/app.ts#L43-L44

Isn't it like this?

```diff
   const exclude = core.getInput('EXCLUE', {required: false}).split(",");
-  core.info(`Excluded languages: ${utcOffset}`);
+  core.info(`Excluded languages: ${exclude.length}`);

```

**Comment by vn7n24fzkq** [comment]
Thank you for the report!
We will fix this in the next release.

**Comment by vn7n24fzkq** [comment]
I think we are already fixing it, so I will close this issue, thanks again.
