### ISSUE TITLE
[Feature request] able to provide an option to combine git commits?

### ISSUE THREAD

**Issue by winsphinx** [vn7n24fzkq/github-profile-summary-cards#157]
After days by days github action flow works, there are many many commits named `Generate profile summary cards`. 

Would they can be combined/ deleted/ merged/ rebased?

**Comment by vn7n24fzkq** [comment]
Hi, @winsphinx.
Yes, we can manually rebase them into one commit.
Considering other GitHub actions might auto-commit in the same repository,  currently, we don't have any feature to do that automatically.

**Comment by vn7n24fzkq** [comment]
However, we can add a feature to reduce the commits, such as if the previous commit was generated from the GitHub action, then rebase it and create a new commit.

**Comment by winsphinx** [comment]
> However, we can add a feature to reduce the commits, such as if the previous commit was generated from the GitHub action, then rebase it into one commit.

Great idea! I hope it come soon.
