### ISSUE TITLE
[Feature request] Improve the Wording in Summary Cards

### ISSUE THREAD

**Issue by Matteas-Eden** [vn7n24fzkq/github-profile-summary-cards#17]
**Context**

The current wording used in the summary cards sounds a little unnatural. There are also a couple minor formatting annoyances, like using lower case where I feel upper case would be more appropriate.

**Alternatives**

An alternative is not available.

**Has the feature been requested before?**

No, it has not been requested before.

**If the feature request is approved, would you be willing to submit a PR?**

Yes.

**Comment by vn7n24fzkq** [comment]
LGTM.
I will merge if there no others disapprove it.
