### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Innu38** [vn7n24fzkq/github-profile-summary-cards#184]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Cheezik** [comment]
interesting.. really confused about the part when ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎  dont work as intended, have you maybe tried ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ 
let me know how it goes, have a great day ^^

**Comment by vn7n24fzkq** [comment]
I'm not sure if this issue was accidentally opened from a template. lol
I will close this issue; please reopen it if it wasn't a mistake.
