### ISSUE TITLE
[Feature request] Add code comments

### ISSUE THREAD

**Issue by sandipkatel** [vn7n24fzkq/github-profile-summary-cards#186]
**Context**

What if there is comment at the summery card generator?
//GenerateProfileSummaryCardsTemplate
const commitFile = async () => {
    await execCmd('git', ['config', '--global', 'user.email', 'profile-summary-cards-bot@example.com']);
    await execCmd('git', ['config', '--global', 'user.name', 'profile-summary-cards[bot]']);
    await execCmd('git', ['add', OUTPUT_PATH]);
    await execCmd('git', ['commit', '-m', 'Generate profile summary cards']);
    await execCmd('git', ['push']);
};
Even it is clear from code it would be easy to anyone not knowing .ts well

**Alternatives**

The function of app.ts can be added at top instead.
//GenerateCards

**Has the feature been requested before?**

Might not be.

**If the feature request is approved, would you be willing to submit a PR?**

Yes- Always open for doing so.

**Comment by vn7n24fzkq** [comment]
I think that's a great idea! Please feel free to submit a PR.
