### ISSUE TITLE
[Feature Request] Add total stars earned

### ISSUE THREAD

**Issue by rogeraabbccdd** [vn7n24fzkq/github-profile-summary-cards#2]
Add total stars earned in stats card.

**Comment by vn7n24fzkq** [comment]
Sounds great.
But there not everyone earned stars on github, we can show it on the current email place if the user earned any star, if not we just display email.
How do you think.

**Comment by rogeraabbccdd** [comment]
Or only show stars when user has stars earned?
I don't think it's a good idea to replace email, even if users can set their email on profile settings.
We need that information when we share stats card to others outside GitHub.

**Comment by vn7n24fzkq** [comment]
I got some ideas.
- Replace public repo when user has stars earned
It will look like this.
![image](https://user-images.githubusercontent.com/20241522/92329431-fb991e80-f099-11ea-9d03-1758b25615af.png)

- Add one more line for user details,if not earned stars, then just display other stuff like location or company.
![image](https://user-images.githubusercontent.com/20241522/92329716-da393200-f09b-11ea-91c5-a370d5d24228.png)

- Create another card for earned stars, PR merged, and all that

**Comment by rogeraabbccdd** [comment]
I think create another card for other stats is the best solution.

**Comment by vn7n24fzkq** [comment]
Sure, I will add this in the next release.

**Comment by vn7n24fzkq** [comment]
Hi, I create a stats card.

**Comment by rogeraabbccdd** [comment]
It looks awesome!

**Comment by vn7n24fzkq** [comment]
Nice, I will release this later.

**Comment by vn7n24fzkq** [comment]
It is release now.
If there are no other problems, may this issue can be closed?

**Comment by rogeraabbccdd** [comment]
Sure
