### ISSUE TITLE
[BUG] Step 2 in the Wiki doesn't show what boxes to check

### ISSUE THREAD

**Issue by jackpurrin** [vn7n24fzkq/github-profile-summary-cards#205]
**Describe the bug**
Step 2 in the Wiki doesn't show what boxes to check.
When on step 2, it says "Name your token (I'd recommend naming it something after profile-summary-cards-token) and ticking these boxes:" but there is no boxes described to be checked.

**To Reproduce**
1. Go to 'Wiki'
2. Click on 'Follow the tutorial [here](https://github.com/vn7n24fzkq/github-profile-summary-cards/wiki/Tutorial).'
3. Scroll down to 'Generate token'

**Expected behavior**
It is supposed to tell you what boxes to check.

**Comment by Cheezik** [comment]
Hey there! im the autor of the wiki, seems like i eigher forgot to put the part after login OR there are no boxes to be checke. ill take a look at it right now, thanks for bringing this up ^^

**Comment by Cheezik** [comment]
Yup, I cropped out the part that was supposted to be displayed after the login. Im working on the edits, Until thats done. the boxes that were ment to be checked are:

repo:status
repo_deployment
public_repo

read:user
user:email

Once again thank you for bringing it to my attention! ^^

**Comment by Cheezik** [comment]
#206

**Comment by vn7n24fzkq** [comment]
I had already merge it, thanks for the issue report and fixing 😀
