### ISSUE TITLE
 [Question]Whats the value of the secret?

### ISSUE THREAD

**Issue by Ryan-samaeian** [vn7n24fzkq/github-profile-summary-cards#21]
Hi i did it,and it didnt load all the cards ;( i just wanted to ask what is the value of the secret

**Comment by vn7n24fzkq** [comment]
@Ryan-samaeian  The value is your personal access token.

**Comment by Ryan-samaeian** [comment]
Hey thanks! i did it,but it still didnt work i did fiill the value with the code and ran the action,but it didnt generator the whole thing.

**Comment by vn7n24fzkq** [comment]
@Ryan-samaeian  That's weird. 🤔
Does the personal access token has these permissions?
|![image](https://user-images.githubusercontent.com/20241522/98506224-f9b82b00-2295-11eb-816a-3450afa49dca.png)|
|-|
![image](https://user-images.githubusercontent.com/20241522/98506232-fcb31b80-2295-11eb-8628-07a806dd4500.png)

**Comment by Ryan-samaeian** [comment]
i did that but its still not working!

**Comment by vn7n24fzkq** [comment]
I notice that you forgot change the secret name in your work flow.
https://github.com/Ryan-samaeian/readme/blob/a523a6c9046b01b7960b8071ed700ab365cf9f32/.github/workflows/profile-summary-cards.yml#L17
You need to change the GITHUB_TOKEN value to your secret name in your repo.

If the secret name is `MY_SECRET`, then the GITHUB_TOKEN should be `secrets.MY_SECRET`.

**Comment by Ryan-samaeian** [comment]
OHHH!
