### ISSUE TITLE
Public Repository stats isn't updating

### ISSUE THREAD

**Issue by FahimFBA** [vn7n24fzkq/github-profile-summary-cards#44]
**Describe the bug**
Whether we create a new public repo / delete a public repo / change the visibility of a private repo to the public one, the stats don't change at all. It always remains exactly the same as earlier.

Check the attached screenshot. If any visitor checks, he/she will find 78 public repos whereas the stats are showing it as only 33 public repo.

![Screenshot (94)](https://user-images.githubusercontent.com/64195132/114315922-febe2680-9b22-11eb-89ed-1210ffc378cd.png)

**Comment by vn7n24fzkq** [comment]
Thanks for your report @FahimFBA 

The generated SVG will cached for 4 hours by server, so it would not update immediately.

And the number of public repos only count repo which was not created by fork.

**Comment by FahimFBA** [comment]
That clarifies the confusion. Thanks a lot!
