### ISSUE TITLE
Includes commits and top language stats for private repos.

### ISSUE THREAD

**Issue by terra9** [vn7n24fzkq/github-profile-summary-cards#5]
Is it possible to have stats for private repo included?

**Comment by vn7n24fzkq** [comment]
Yes, default setting is include private.
But `secrets.GITHUB_TOKEN` token doesn't have permission for private so you need use your Personal access token instead.
[Creating a personal access token
](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token)
[Creating and storing encrypted secrets
](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)

[The token need those permission](https://github.com/vn7n24fzkq/github-profile-summary-cards/wiki/Personal-access-token-permissions)

**Comment by terra9** [comment]
I will try it out. 
Don't close the issue, I will do it, after trying your comment.
