### ISSUE TITLE
[Feature request] Add a default case for theme parameter

### ISSUE THREAD

**Issue by kaustubhgupta** [vn7n24fzkq/github-profile-summary-cards#53]
**Context**

For most of the GitHub stats, we don't need to provide any additional parameters to generate stats. For instance:

`https://github-readme-stats.vercel.app/api?username=kaustubhgupta`: Anurag Hazra's [GitHub stats](https://github.com/anuraghazra/github-readme-stats)

I was wondering if something similar could be implemented for this project where I visit this URL:
`https://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=kaustubhgupta` without any theme parameter and I still get the stats image. 

You can choose any of the already available themes as default. 

**If the feature request is approved, would you be willing to submit a PR?**

I can't as I work on a different tech stack :(

**Comment by vn7n24fzkq** [comment]
Sure, we can add a default value for theme.

We only need to add the default value for theme parameter in all API in cards.
https://github.com/vn7n24fzkq/github-profile-summary-cards/blob/a8a74c780d878380eb185f1144f8a992192d3fde/api/cards/productive-time.js#L8

And write something like this.

```javascript
 const { username, theme="default" } = req.query;
```

**Comment by kaustubhgupta** [comment]
If this is that simple, can I make the PR for the same?

**Comment by vn7n24fzkq** [comment]
Yes, you can.
