### ISSUE TITLE
[Feature request] configurable timezone 

### ISSUE THREAD

**Issue by kerthcet** [vn7n24fzkq/github-profile-summary-cards#56]
**Context**
Now timezone is default to UTC, it should be configurable. 

**Alternatives**

If I missed something, please let me know. Thanks.

**Has the feature been requested before?**

I searched all issues, nothing found.

**If the feature request is approved, would you be willing to submit a PR?**

Yes

**Comment by kerthcet** [comment]
> I am prefer to make another card with average commit number, it would be more make sense, average commits number charts is not looks good for every people.
> 
> How do you think?
IMO, if we plan to add filter params, we can redesign the card with options of `yearly`, `monthly`, `three monthly`, `daily` and so on. maybe `daily` default.

> 
> We can add timezone parameter first and see how it would be.
> 
> Would you like to submit a PR for timezone parameter?
yeah, I would like to have a try. Since I'm busy with my projects, feature will not be complete soon.

**Comment by kerthcet** [comment]
> I am prefer to make another card with average commit number, it would be more make sense, average commits number charts is not looks good for every people.
> 
> How do you think?

IMO, if we plan to add filter params, we can redesign the card with options of `yearly`, `monthly`, `three monthly`, `daily` and so on. maybe `daily` default.

> 
> We can add timezone parameter first and see how it would be.
> 
> Would you like to submit a PR for timezone parameter?

yeah, I would like to have a try. Since I'm busy with my projects, feature will not be complete soon.

**Comment by kerthcet** [comment]
do you have a plan about the feature/timezone-parameter? Deadline maybe.

**Comment by vn7n24fzkq** [comment]
Because I am planning to do some code refactor recently, can we finish the feature/timezone-parameter in one month? 

After that, I can redesign cards when I do the code refactor.

**Comment by vn7n24fzkq** [comment]
We can add the timezone as an optional parameter in GitHub Actions, if this usage is okay, then we can do the same thing on  other parameters.

**Comment by kerthcet** [comment]
ok, I'll have a try. Thanks @vn7n24fzkq
