### ISSUE TITLE
Rewriting in TypeScript

### ISSUE THREAD

**Issue by vn7n24fzkq** [vn7n24fzkq/github-profile-summary-cards#63]
A strongly typed programming language would be easier to maintain and for reading.

**Comment by vn7n24fzkq** [comment]
Unfortunately, I didn’t have time to finish it until January 3rd.😢

**Comment by iamandrewluca** [comment]
After rewriting to TypeScript, would be nice to have SVGs created using a more declarative way (JSX) instead of D3 👀
