### ISSUE TITLE
[Feature request] Add Transparent theme

### ISSUE THREAD

**Issue by mqliang** [vn7n24fzkq/github-profile-summary-cards#73]
**Context**

With the introduction of dark mode in Github it has become difficult to set an image background that looks consistent with the background in both dark and light mode.

To solve this the most obvious solution was to make the background transparent. All that was left was to choose colors for text that makes it legible in light as well as dark background.

Is it possible to add a "Transparent theme" so that it looks good on both light and dark Github mode?

FYI. Here is a PR add a Transparent theme to github-readme-stats
project: anuraghazra/github-readme-stats#1010

**Alternatives**

Can you achieve the same result doing it in an alternative way? Is the alternative considerable?

**Has the feature been requested before?**

Please provide a link to the issue.

**If the feature request is approved, would you be willing to submit a PR?**

Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by vn7n24fzkq** [comment]
Closed by #126, thanks @yamashush

**Comment by yamashush** [comment]
;)
