### ISSUE TITLE
New color themes

### ISSUE THREAD

**Issue by manojuppala** [vn7n24fzkq/github-profile-summary-cards#77]
**Context**

Currently there are only limited number of color themes. Are you planning to add more?

**If yes, i would like to submit a PR.**

New themes i would like to add : 
- radical (#66 )
- gruvbox
- tokyonight
- cobalt
- dark

**Comment by vn7n24fzkq** [comment]
Hi, @manojuppala 
We do plan to add more color themes, and we are welcome any PR for that.
But currently, the code is running in a huge refactoring and I will recommend you do this after #72 merged.

**Comment by vn7n24fzkq** [comment]
Or you can just create another branch from this branch `refactor/rewriting-in-typescript` and we can merge the PR into master if you submit it.
