### ISSUE TITLE
[BUG] Error: Error: git push,  Invalid status code: 1

### ISSUE THREAD

**Issue by dongzl** [vn7n24fzkq/github-profile-summary-cards#87]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

```
UTC offset: 8
Remove old cards...
Creating ProfileDetailsCard...
Creating ReposPerLanguageCard...
Creating CommitsPerLanguageCard...
Creating StatsCard...
Creating ProductiveTimeCard...
Creating preview markdown...
Commit file...
Warning: Commit failed. Retry...
Warning: Commit failed. Retry...
Error: Error: git push 
  
 Invalid status code: 1
Error: git push 
  
 Invalid status code: 1
```

**Comment by vn7n24fzkq** [comment]
Hmm, this bug happened randomly, I will continue to focus on this issue.

**Comment by vn7n24fzkq** [comment]
We add a new write required permission in action now, it should be fixed.
https://github.com/vn7n24fzkq/github-profile-summary-cards#github-actions-usage
