### ISSUE TITLE
[Feature request] Exclude specific repositories from the Top Languages card

### ISSUE THREAD

**Issue by VianaSamuel** [vn7n24fzkq/github-profile-summary-cards#91]
I think the title says by itself. It would be a really useful feature!
I saw it (exclude_repo) on [this similar repo](https://github.com/anuraghazra/github-readme-stats#language-card-exclusive-options).

**Comment by vn7n24fzkq** [comment]
We just release it out, 
Please take a look, https://github.com/vn7n24fzkq/github-profile-summary-cards#top-languages-in-commits-card
