### ISSUE TITLE
[Feature request] able to hide languages on cards

### ISSUE THREAD

**Issue by RodrigoDornelles** [vn7n24fzkq/github-profile-summary-cards#94]
**Context**

being able to remove languages on cards, as well as markup and others that there is no interest in showing personalized by the url.

**Alternatives**

using URI param  `hide=html,css`

**If the feature request is approved, would you be willing to submit a PR?**

Yes

**Comment by MiranDaniel** [comment]
I'd also like this feature and would like to help out if possible!

**Comment by vn7n24fzkq** [comment]
Sorry for the late reply.

Yes! We can add the feature.

For the implementation details, we can just hide the languages or ignore languages from the counting.

How do you think?

**Comment by MiranDaniel** [comment]
Think it would be better to just ignore them from counting, that way the pie chart is always filled at 100%.

**Comment by vn7n24fzkq** [comment]
Sounds good, I had the same thought.

**Comment by MiranDaniel** [comment]
Currently working on implementing this, will most likely submit a PR by the end of the week

**Comment by vn7n24fzkq** [comment]
Nice! 
We will need to add an optional parameter to GitHub Action usage in action.yml and an URL query parameter in API.
Because we don't have any development documents right now, and the code is a little mess, so feel free to ask any questions.

**Comment by MiranDaniel** [comment]
Is there any way to locally run the API server? I'd like to test it as well before making a PR

**Comment by vn7n24fzkq** [comment]
https://vercel.com/blog/vercel-dev
 I use 'vercel dev'
 It may ask you to deploy your own version on vercel, so here are some settings.

![Screenshot_20220709-135945~2.png](https://user-images.githubusercontent.com/20241522/178093809-54011e2f-9fd4-46d0-b639-3483ee527fd5.png)

**Comment by MiranDaniel** [comment]
Awesome, got it deployed at https://github-profile-summary-cards-psi.vercel.app/ , just need to make the demo page now!

Example: https://github-profile-summary-cards-psi.vercel.app/api/cards/repos-per-language?username=MiranDaniel&theme=default&hidden=python,html

Want me to make a PR now and then later with the demo page or should I submit it when it's both ready?

**Comment by vn7n24fzkq** [comment]
Great! 
We can create another PR for the demo page.
By the way, I think maybe using `exclude` instead of `hidden` will be a more precise word for this feature. 🤔 
Not sure would we need the `include` in the future.

**Comment by vn7n24fzkq** [comment]
But the `hidden` word is okay to me, use `exclude` and `include` at the same time may be confused and have to deal with some tricky problems.

**Comment by MiranDaniel** [comment]
Not sure if we will need `include` but I don't really think so, nobody really has so many languages that they cannot just list them out all in `hidden` and if they do, then their summary card isn't very meaningful. 
`exclude` does sound like a better name than `hidden` though.

**Comment by vn7n24fzkq** [comment]
I have the same thought

**Comment by MiranDaniel** [comment]
Renamed to `exclude`, created #97

**Comment by RodrigoDornelles** [comment]
> Great! We can create another PR for the demo page. By the way, I think maybe using `exclude` instead of `hidden` will be a more precise word for this feature. 🤔 Not sure would we need the `include` in the future.

i think the parameter name `hidden` is great, because exist another's projects be like.

**Comment by vn7n24fzkq** [comment]
> > Great! We can create another PR for the demo page. By the way, I think maybe using `exclude` instead of `hidden` will be a more precise word for this feature. 🤔 Not sure would we need the `include` in the future.
> 
> i think the parameter name `hidden` is great, because exist another's projects be like.

To me, `exclude` would be more accurate than `hidden`, cuz we do not calculate the specific languages and not just hide from the chart.

But consider that user can learn the option usage from other similar projects and we also don't need `include` actually, `hidden` is a good word too.

**Comment by vn7n24fzkq** [comment]
@MiranDaniel What do you think?

**Comment by RodrigoDornelles** [comment]
@vn7n24fzkq Why can't I use it yet?

It's already been merged, and I'm trying to test it.

![](http://github-profile-summary-cards.vercel.app/api/cards/repos-per-language?username=rodrigodornelles&theme=nord_dark&exclude=html,css)
| :-: |
| `http://github-profile-summary-cards.vercel.app/api/cards/repos-per-language?username=rodrigodornelles&theme=nord_dark&exclude=html,css` |

**Comment by vn7n24fzkq** [comment]
Hi, @RodrigoDornelles.
Because we haven't made a release version yet.
It will be released soon.

**Comment by vn7n24fzkq** [comment]
I reopened this issue until we actually release this feature.

**Comment by kerthcet** [comment]
+1 for the feature, and maybe better to explain in the readme on which release this will be available, to avoid such confusing also saves your time. :)

**Comment by vn7n24fzkq** [comment]
Sorry for not getting back to you sooner, we are just drafting a release now!
So I think we can close this issue.
